name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List Directory
        working-directory: scripts 
        run: ls
      
      - name: Dependency install
        working-directory: "source code/t3-frontend"
        run: |
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: subash-artifact
          path: "source code/t3-frontend/build"  # Change this to the directory you want to upload
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
