name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List Directory
        working-directory: scripts 
        run: ls
      
      - name: Dependency install
        working-directory: "source code/t3-frontend"
        run: |
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: subash-artifact
          path: "source code/t3-frontend/build"
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

  download_artifact:
    runs-on: self-hosted
    needs: [install_and_build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: subash-artifact
          path: ./downloaded-artifact

      - name: List downloaded artifact
        run: ls ./downloaded-artifact

      - name: Create target directory
        run: |
            mkdir -p $HOME/Artifacts
            mv ./downloaded-artifact/* $HOME/Artifacts
            ls -al $HOME/Artifacts
